# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [1]:
import numpy as np
import random



1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
arr = np.linspace(0,20, 4*7).reshape(4,7)
arr/20+0

array([[0.        , 0.03703704, 0.07407407, 0.11111111, 0.14814815,
        0.18518519, 0.22222222],
       [0.25925926, 0.2962963 , 0.33333333, 0.37037037, 0.40740741,
        0.44444444, 0.48148148],
       [0.51851852, 0.55555556, 0.59259259, 0.62962963, 0.66666667,
        0.7037037 , 0.74074074],
       [0.77777778, 0.81481481, 0.85185185, 0.88888889, 0.92592593,
        0.96296296, 1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
matrix = np.random.randint(0,10, 8*10).reshape(8,10)
summ = sum(matrix[0])
l = 0
for i in range(len(matrix)):
    if sum(matrix[i])>= summ:
        l = i
        summ = sum(matrix[i])
        
print(f'Строка с номером {l}, ее сумма: {summ}')
matrix

Строка с номером 6, ее сумма: 51


array([[4, 2, 6, 1, 4, 4, 6, 2, 4, 5],
       [6, 3, 0, 0, 3, 5, 2, 7, 9, 9],
       [2, 6, 1, 1, 9, 7, 2, 1, 4, 3],
       [4, 5, 3, 6, 5, 8, 8, 2, 8, 1],
       [4, 2, 4, 5, 2, 8, 8, 0, 1, 8],
       [9, 2, 6, 1, 7, 1, 6, 7, 3, 8],
       [4, 9, 6, 5, 4, 6, 3, 9, 5, 0],
       [0, 8, 4, 0, 3, 2, 6, 7, 2, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
point_1 = np.array((0, 0, 0))
point_2 = np.array((3, 3, 3))

square = np.square(point_1 - point_2)
sum_square = np.sum(square)
distance = np.sqrt(sum_square)

distance

5.196152422706632

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [5]:
A = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B= np.matrix([[3, -1], [2, 1]])
C= np.matrix([[7, 21], [11, 8], [8, 4]])

np.matmul(np.matmul(np.linalg.inv(A), (-C)), np.linalg.inv(B))

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

# Новый раздел

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [6]:
import numpy as np
data = np.loadtxt("minutes_n_ingredients.csv",skiprows=1, delimiter=',', dtype=np.int32)
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [7]:
column = 1
print(f"Минимальное: {np.min(data[:, column])}", f"Максимальное: {np.max(data[:, column])}", f'Среднее: {np.mean(data[:, column])}', f"Медиана: {np.median(data[:, column])}", sep='\n', end='\n\n')
column = 2
print(f"Минимальное: {np.min(data[:, column])}", f"Максимальное: {np.max(data[:, column])}", f'Среднее: {np.mean(data[:, column])}', f"Медиана: {np.median(data[:, column])}", sep='\n', end='\n\n')



Минимальное: 0
Максимальное: 2147483647
Среднее: 21601.00169
Медиана: 40.0

Минимальное: 1
Максимальное: 39
Среднее: 9.05528
Медиана: 9.0



3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [8]:
time_out = data.copy()
q_3 = np.quantile(time_out[:, 1], q=0.75, axis=0)
time_out[:, 1][time_out[:, 1] > q_3] = q_3

print(time_out)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
without_0 = time_out.copy()
good_day = without_0[:, 1] == 0
zero = np.count_nonzero(good_day)
without_0[:, 1][good_day] = 1

print(zero)
print(without_0)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
unique_items = np.unique(without_0[:, 1:], axis=0).shape[0]
print(unique_items)

1135


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [11]:
print(len(np.unique(without_0[:, 2])))

37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [12]:
without_0[without_0[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [13]:
temp = without_0.copy()
result = (temp[:,2]/temp[:,1])
print("Ингридиентов на одну минуту рецепта: ",result)
print('Максимальное значение: ',result.max())

Ингридиентов на одну минуту рецепта:  [0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462]
Максимальное значение:  24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [14]:
long_recept = np.argsort(without_0[:, 1])[:-100:-1]
without_0[long_recept][:, 2].mean()

9.94949494949495

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [15]:
data[np.random.randint(data.shape[0], size=10), :]

array([[325427,     75,     15],
       [ 41272,     15,      9],
       [158853,     35,      9],
       [256099,    365,      8],
       [287747,     20,      8],
       [ 45680,      4,      7],
       [184029,     70,      6],
       [217128,   1440,      7],
       [235117,     75,      8],
       [342190,     30,     10]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [16]:
not_bad_percent = without_0[long_recept][:, 2].mean()
good_day = data[:, 2] < not_bad_percent
print(len(data[good_day])/len(data) * 100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [17]:
single = np.where((data[:,1]<=20) & (data[:,2]<=5), 1, 0)
dataset12 = np.column_stack((data, single))
dataset12

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [18]:
np.sum(dataset12[:, 3]==1)/data[:,0].size * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [19]:
short = data[data[:, 1]<10, :]
standart = data[np.where((10<=data[:, 1]) & (data[:, 1]<20)), :]
long = data[20<=data[:, 1], :]

len_rec = min(short.size,long.size,standart.size)//3

short_id = short[:len_rec, 0]
standart_id = standart[:len_rec, 0]
long_id = long[:len_rec, 0]

# print(standart_id.shape)

short_rec = short[:len_rec, 1:]
standart_rec = standart[1:, :len_rec]
long_rec = long[:len_rec, 1:]

dataset14_short = np.array([short_id])
dataset14_standart = np.array(standart_id)
dataset14_long = np.array([long_id])
dataset14_standart


array([[94746,    10,     6]], dtype=int32)